### ISSUE TITLE
[SECURITY] ip address is NOT encrypted!

### ISSUE THREAD

**Issue by CMDR-JohnAlex** [CMDR-Piboy314/3D-Multiplayer-FPS-Godot#1]
## [SECURITY] ip address is NOT encrypted!

If you open the exe in a text editor, you can see that our ip address is NOT encrypted (Press ctrl+f and type our ip address).

**Possible fix:** Remove our ip address from the code and add a text box that will get input for the ip address that will be used.

(Screenshots and location of ip address will not be added for security reasons)

**Comment by CMDR-Piboy314** [comment]
Note: This is not true and was a prank

**Comment by CMDR-JohnAlex** [comment]
@CMDR-Piboy314 
Please watch this video linked below and **TRY** what I have said to do, a _good_ developer would get worried when someone says their IP address is **leaked** and would **TRY** to see if the issue is true. **Clearly, you have not tried** what I have said to do, watch this video and see what I mean. 
https://drive.google.com/file/d/1QqsGPym9PTEq_mUuaHFWadsii30UFlBx/view?usp=sharing
This video is showing our IP address, the only way to remove the ip address and this issue from github the best you can is to delete this repository.

**If proper action is not taken in the next few hours, I will have to email github support to remove this repository and remove all sesitive information.**
